apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/vrutkovs/ota-argocd-config
      passwordSecret:
        name: private-repo-creds
        key: password
      usernameSecret:
        name: private-repo-creds
        key: username
    - url: https://github.com/vrutkovs/havi
      passwordSecret:
        name: private-repo-creds
        key: password
      usernameSecret:
        name: private-repo-creds
        key: username
    - url: https://github.com/vrutkovs/huginn
      passwordSecret:
        name: private-repo-creds
        key: password
      usernameSecret:
        name: private-repo-creds
        key: username
    - url: https://github.com/vrutkovs/gersemi
      passwordSecret:
        name: private-repo-creds
        key: password
      usernameSecret:
        name: private-repo-creds
        key: username
    - url: https://github.com/vrutkovs/eir
      passwordSecret:
        name: private-repo-creds
        key: password
      usernameSecret:
        name: private-repo-creds
        key: username
    - url: https://github.com/vrutkovs/ota-pipeline-sandbox
      passwordSecret:
        name: private-repo-creds
        key: password
      usernameSecret:
        name: private-repo-creds
        key: username
