apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: slack-alert-config
spec:
  receivers:
    - name: slack-notifications
      slackConfigs:
        - apiURL:
            key: apiURL
            name: alert-slack
          channel: '#general'
          color: |-
            {{ if eq .Status "firing" -}}
                {{ if eq .CommonLabels.severity "warning" -}}
                    warning
                {{- else if eq .CommonLabels.severity "critical" -}}
                    danger
                {{- else -}}
                    #439FE0
                {{- end -}}
            {{ else -}}
            good
            {{- end }}
          text: |-
            {{ range .Alerts }}{{ .Annotations.description }}
            {{ end }}
          title: |-
            {{ range .Alerts }}{{ .Annotations.summary }}
            {{ end }}
  route:
    receiver: slack-notifications
