apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scrape-stats
spec:
  endpoints:
    - interval: 30s
      port: web
      scheme: http
  namespaceSelector: {}
  selector:
    matchLabels:
      app: stats
