kind: Service
apiVersion: v1
metadata:
  name: stats
  labels:
    app: stats
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    tekton.dev/pipeline: build-reports
    tekton.dev/pipelineTask: stats
  type: ClusterIP
