kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: havi-edit
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: havi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-aggregate-edit
