apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: private-repo-creds
  namespace: openshift-gitops
spec:
  encryptedData:
    password: AgAzw5yizFJu21tYupDIzmUk4RLAfqmEa34r67Vc1yAoJ3ZUpQhVBZLiI+qHKspwxx/q8t+RJLWolVqjQW9YH0ZmdtPoidTNVC2ak+cioYlcXHYWrf9vaNuYc9vEP9jxiGZgKIanSulZWfmfO7C5CaenEdvDLWVtbKAUyIrCR1R1FAYWHDAJqDObjuDSLuv4jPqvIP7B1bdUymBm58giYrfDHZo00hqrFHGOoyio52seM8u1ok3aK/yJhsUgXtQV/4vojpYRTVjd3cPiOQ1JRoynQvwnkWeleqncQmmEVMlr4ntkjnjgYXB4eZ06NAJUmrfy3TCrw0LKjZNwIb/1X63656idhIMsqH6li4pXRX9uYwJUvQG4C3BhJzrQPleAveCaW69kXoxhhh8bTLHnh1hCDk4X3aweMhtBBvx5j/Dxe8ynaOlULeuZqpKN5i2yswXclq9K3GVDiPhkvlh0yz8i7aNCqfsxv/61hH/XmndmrJtLIxLpRhnZ0wynwnmOKtEyOfCONV0+Z8ULiLxTbEybrnDDysbQU95c3IFY1il+Lo/gDicuwTrir/m9GdLKselbiptflO8spalaw7gDsXFdsjeluEzzOquVdxWKx7VgNO2Iea57MU3Pd7np2+SH0SPTLUZtYkasbTLkmsR/46y4gcUU4gXnnBoCE071RkpJ28V2zC51HK5nT1CNUP8iI8TxO+XMIuYmgMMus05k0CNXT1QqVEtEfZa5ZvaVRMG22q7LpjNIDK/S
    url: AgBTjzlRUSCJhDlDvbH3nBP1/inXjwhrL4bJySsVjIkcbDY3c5r1JxByxtm60A+7jZlq57TXgcrRocXFjIi+02neaY2rm8rofdA8bJdG9j9M5fWKbF8mAzFcHp+bCkwVNbs4Zq08DtcI/aba/s2zqtFVI4yFgblvZcBW1eyPbzvgz+Jh98976XeuxDW4hRTIgD/ecPqhcZuD70jWt3F1ZftdTuJXiXfyM6NEnDoS3xyF0MpuwbUWJMjKuN8UZS1LQddmIbwjRfsU2HVuVwIH7jY2j9DveJIhLDBHGzTIIPOgnKqKc2HzjZpb/nZPllLfnwfOFOxqhnei1jxtvFuZQvoGagRtdEatk2XSm3Thm95V9Kucywmei3GBohGDS1FUgUEzJZcVTOs1xyEsANQ1Hci3HoUOh2KT2dmMa5bHP6OBZNJOPWlMaG45O9o/AF2VMeJxes3zYXuSizQgn7mimBsJCqGVWi7UD86xK951hscR0Wiska71TT4qwPObL61oykPOHrUuejY+ZGvXcfbrXo6dA2hGOFo5BR9akPeY+oa+NQ6dQaFcETT/VT/tovFasAWvhVgzJVMjfpIv527LkBNc67ddRok358kU0CRmfzehy3u0OXz+B5kH7PTraetfWHU05QQWH81ix8rrl9LPuBlM3ysy/524Cc2ll5g5Mn6b8vGll32NZZMuMYN+tdUtxe85cah0u//4td4pxH7/YBpFCBfEjKo2Bm6+yQg=
    username: AgCHzK2URqyof0Ve9X/ZisCwipTqQQgmQBL+gghLwZg/xZKjkV0JcZ6nXPPc9BjQHDakyRBu5Lfo3GyyerMDcG5jksXIFTo1QNilIWxeI/T1ArvUNkuYBBS2UlCqHRQHKXWpD5ZvaUEjc1ZwYk0J5CTn/rO4LJD2jW+7OIg3i86ZMo2HXjvvraPPJOlgpJ0ICYsBXSWKQTd8J5pTUO4DgiXmw4/IIG7X5WTDEo6iRaxpdjJnXBKrrvQistgyvpBtO6MmjYGSELkh9INT0dZd7wShHh3mPuVOvj7JPpopyVqrTmNUZ4hVBoRgjW8EXiTP9nzfl+0EgH96i70vMn/p7Xm3JIs8Ru+cINQ/C/JRr1UO/5JapHGnrKl0evQ8fKVHMGLR1WDH4dgG+ednxZABhvx8DpcvZktOblbQ20hB3JUe0OASn/QLGGEmX89QSOFZk3MlEDndXgLP2AZ7YNI42vs8cnp1EE4IONrSKIfyd4826x3cFW6XydqcY7Wxe9C6VcQTOVzhM6Ah6ajzBgE7DGTKAUc1QytfFCAety6sB+ZBDBDoUpWd5+dIMK25OBCqegKCSTAQQF4zGaknzP1XlMKzsDeQSQjsFHEVa2jGXTbTNR9JyA/cGQFvr3pJzmup2jdAddVXYCQdLu7wp4pRi588AG+al8h+88tHs1Y5rkd7FHEXEDIRHBZOzonU6B53D4ZWkEq5vNLl0A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-cm
        app.kubernetes.io/part-of: argocd
        argocd.argoproj.io/secret-type: repo-creds
      name: private-repo-creds
      namespace: openshift-gitops

