kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s3-proxy
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 's3-proxy:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:latest'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: >
      FROM registry.access.redhat.com/ubi8/nginx-118

      USER 0

      ADD . /tmp/src

      RUN chown -R 1001:0 /tmp/src

      USER 1001

      RUN /usr/libexec/s2i/assemble

      CMD /usr/libexec/s2i/run
    configMaps:
      - configMap:
          name: nginx-config
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
