kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';


        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        include /opt/app-root/etc/nginx.d/*.conf;

        proxy_cache_path   /tmp/ levels=1:2 keys_zone=s3_cache:10m max_size=500m
                           inactive=60m use_temp_path=off;

        server {
            listen       8080 default_server;
            listen       [::]:8080 default_server;
            server_name  _;

            # Load configuration files for the default server block.
            include /opt/app-root/etc/nginx.default.d/*.conf;

            location = / {
              index index.html;
            }

            location / {
              try_files $uri @awss3;
            }

            set $backend "ota-reports-stage.s3.amazonaws.com";

            location @awss3 {
              resolver 8.8.8.8;
              proxy_http_version 1.1;
              proxy_set_header Authorization '';
              proxy_set_header Host $backend;
              proxy_pass http://$backend/$uri;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_hide_header x-amz-id-2;
              proxy_hide_header x-amz-request-id;
              proxy_hide_header Set-Cookie;
              proxy_ignore_headers Set-Cookie;
              proxy_intercept_errors on;
              proxy_buffering off;
            }
        }
    }
