kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';


        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        include /opt/app-root/etc/nginx.d/*.conf;

        server {
            listen       8080 default_server;
            listen       [::]:8080 default_server;
            server_name  _;

            # Load configuration files for the default server block.
            include /opt/app-root/etc/nginx.default.d/*.conf;

            location = / {
              index index.html;
            }

            location / {
              try_files $uri @wasabi;
            }

            set $backend "http://s3.eu-central-1.wasabisys.com:80";

            location @wasabi {
              resolver 8.8.8.8;
              proxy_set_header Host 's3.wasabisys.com';
              proxy_pass $backend/ota-reports-temp$uri;
              proxy_intercept_errors on;
              proxy_redirect off;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_hide_header x-amz-id-2;
              proxy_hide_header x-amz-request-id;
              proxy_hide_header content-type;
            }
        }
    }
