apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-proxy
  namespace: openshift-gitops
spec:
  destination:
    namespace: s3-proxy
    server: 'https://kubernetes.default.svc'
  project: ota
  source:
    path: apps/s3-proxy
    repoURL: 'https://github.com/vrutkovs/ota-argocd-config'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: s3-proxy
    namespace: s3-proxy
    jsonPointers:
    - /spec/template/spec/containers/0/image
